version: "3"
services:

  nginx:
    container_name: nginx
    build:
      context: nginx/.
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always


  shinyproxy:
      build:
        context: shinyproxy/.
        dockerfile: Dockerfile
      depends_on:
        - nginx
      container_name: shinyproxy_server
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
      external:
        name: sp-net

  
