version: "3"
services:

  nginx:
#    container_name: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 8080:8080
    restart: always


  shinyproxy:
      build:
        context: .
        dockerfile: shinyproxy.Dockerfile
      depends_on:
        - nginx
      container_name: shinyproxy_server
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
     external:
      name: sp-net

  
